In [1]:
import requests

# Define the URL
url = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?key=AIzaSyDevjJ6bMgOjrSR0hJeJ4TAzo4SyVXzyIU'

# Define the headers
headers = {
    'Content-Type': 'application/json'
}

# Define the data payload
data = {
    "contents": [
        {
            "parts": [
                {
                    "text": "make me a questionnire for a new employee"
                }
            ]
        }
    ]
}

# Make the POST request
response = requests.post(url, headers=headers, json=data)

# Print the response
print(response.json())

{'candidates': [{'content': {'parts': [{'text': '## New Employee Questionnaire\n\n**Welcome to [Company Name]!** \n\nThis questionnaire is designed to help us get to know you better and ensure a smooth onboarding experience. Please answer the following questions honestly and to the best of your ability.\n\n**Personal Information:**\n\n1. **Full Name:**\n2. **Date of Birth:**\n3. **Email Address:**\n4. **Phone Number:**\n5. **Preferred Communication Method:** (Email, Phone, Text)\n6. **Emergency Contact Name & Phone Number:**\n\n**Employment Information:**\n\n7. **Job Title:**\n8. **Department:**\n9. **Start Date:**\n10. **Reporting Manager:**\n11. **Previous Work Experience:** (List your previous 2-3 roles, including company name, job title, and responsibilities)\n12. **Relevant Skills & Qualifications:** (Highlight any skills or qualifications directly relevant to your new role)\n\n**Onboarding & Training:**\n\n13. **What are your learning preferences?** (e.g., hands-on, visual, auditory)\n14. **Are there any specific training topics or areas you would like to focus on during your onboarding?**\n15. **Do you have any questions or concerns about your new role or the onboarding process?**\n\n**Company Culture & Expectations:**\n\n16. **What are your expectations of the company culture?** (e.g., collaborative, fast-paced, results-oriented)\n17. **What are your personal goals for this new role?**\n18. **What are your preferred methods for receiving feedback?** (e.g., one-on-one meetings, email)\n\n**Technology & Equipment:**\n\n19. **Do you have any technical skills or software experience that is relevant to this role?**\n20. **Do you need any specific equipment or software for your role?** \n21. **Do you have any special access requirements for company systems or networks?**\n\n**Other:**\n\n22. **Do you have any hobbies or interests outside of work?**\n23. **Is there anything else we should know about you to help ensure a successful start?**\n\n**Thank you for completing this questionnaire!** Your responses will help us create a customized onboarding experience that is tailored to your needs. \n\n**Please return this completed questionnaire to [Contact Person/Email Address] by [Deadline].**\n\n**We look forward to welcoming you to the team!**\n'}], 'role': 'model'}, 'finishReason': 'STOP', 'index': 0, 'safetyRatings': [{'category': 'HARM_CATEGORY_SEXUALLY_EXPLICIT', 'probability': 'NEGLIGIBLE'}, {'category': 'HARM_CATEGORY_HATE_SPEECH', 'probability': 'NEGLIGIBLE'}, {'category': 'HARM_CATEGORY_HARASSMENT', 'probability': 'NEGLIGIBLE'}, {'category': 'HARM_CATEGORY_DANGEROUS_CONTENT', 'probability': 'NEGLIGIBLE'}]}], 'usageMetadata': {'promptTokenCount': 10, 'candidatesTokenCount': 524, 'totalTokenCount': 534}}

In [47]:
text = response.json()['candidates'][0]['content']['parts'][0]['text']

In [48]:
text

"## New Employee Questionnaire\n\n**Welcome aboard!** We're thrilled to have you join our team. This questionnaire is designed to help us get to know you better and ensure a smooth onboarding experience. Please answer the following questions to the best of your ability.\n\n**Personal Information:**\n\n1. **Full Name:**\n2. **Date of Birth:**\n3. **Contact Information:**\n    * Phone Number:\n    * Email Address:\n    * Personal Address:\n4. **Emergency Contact Information:**\n    * Name:\n    * Relationship:\n    * Phone Number:\n5. **Are you authorized to work in [Country/Region]?** (Yes/No)\n6. **Do you have any disabilities that we should be aware of?** (Yes/No)\n    * If yes, please provide details and any reasonable accommodations you require:\n\n**Employment History:**\n\n7. **Previous Employer:**\n8. **Job Title:**\n9. **Dates of Employment:**\n10. **Reason for Leaving:**\n11. **Relevant Skills & Experience:**\n\n**Position Specific:**\n\n12. **What are your expectations for this role?**\n13. **What are your strengths and weaknesses related to this position?**\n14. **What are your goals for the first 30/60/90 days in this role?**\n15. **Are there any specific areas of the job you are particularly interested in or excited about?**\n16. **Do you have any prior experience with our company's products/services?** (Yes/No)\n    * If yes, please elaborate:\n\n**Company Culture & Team:**\n\n17. **What are some of your preferred ways to work in a team setting?**\n18. **How do you typically approach new challenges or projects?**\n19. **What are your preferred methods of communication?** (Email, phone, in-person, etc.)\n20. **What is your preferred learning style?**\n\n**Availability & Schedule:**\n\n21. **What is your preferred work schedule?** (Full-time, part-time, flexible, etc.)\n22. **Are you available for overtime or weekend work?** (Yes/No)\n\n**Miscellaneous:**\n\n23. **Do you have any questions for us?**\n24. **Is there anything else we should know about you that may be relevant to your role?**\n\n**Thank you for completing this questionnaire. We look forward to having you on board!**\n\n**Note:** This questionnaire is a template and can be customized to fit your specific needs and the requirements of the new position. You can add or remove questions based on your company's culture, industry, and the specific role being filled.  \n"

In [49]:
text_with_new_lines = text.replace('\\n', '\n')
print(text_with_new_lines)

## New Employee Questionnaire

**Welcome aboard!** We're thrilled to have you join our team. This questionnaire is designed to help us get to know you better and ensure a smooth onboarding experience. Please answer the following questions to the best of your ability.

**Personal Information:**

1. **Full Name:**
2. **Date of Birth:**
3. **Contact Information:**
    * Phone Number:
    * Email Address:
    * Personal Address:
4. **Emergency Contact Information:**
    * Name:
    * Relationship:
    * Phone Number:
5. **Are you authorized to work in [Country/Region]?** (Yes/No)
6. **Do you have any disabilities that we should be aware of?** (Yes/No)
    * If yes, please provide details and any reasonable accommodations you require:

**Employment History:**

7. **Previous Employer:**
8. **Job Title:**
9. **Dates of Employment:**
10. **Reason for Leaving:**
11. **Relevant Skills & Experience:**

**Position Specific:**

12. **What are your expectations for this role?**
13. **What are your strengths and weaknesses related to this position?**
14. **What are your goals for the first 30/60/90 days in this role?**
15. **Are there any specific areas of the job you are particularly interested in or excited about?**
16. **Do you have any prior experience with our company's products/services?** (Yes/No)
    * If yes, please elaborate:

**Company Culture & Team:**

17. **What are some of your preferred ways to work in a team setting?**
18. **How do you typically approach new challenges or projects?**
19. **What are your preferred methods of communication?** (Email, phone, in-person, etc.)
20. **What is your preferred learning style?**

**Availability & Schedule:**

21. **What is your preferred work schedule?** (Full-time, part-time, flexible, etc.)
22. **Are you available for overtime or weekend work?** (Yes/No)

**Miscellaneous:**

23. **Do you have any questions for us?**
24. **Is there anything else we should know about you that may be relevant to your role?**

**Thank you for completing this questionnaire. We look forward to having you on board!**

**Note:** This questionnaire is a template and can be customized to fit your specific needs and the requirements of the new position. You can add or remove questions based on your company's culture, industry, and the specific role being filled.

In [50]:
import re

# Assuming 'text' is a string variable containing the text with Markdown syntax
text_with_new_lines = text.replace('\\n', '\n')

# Remove common Markdown syntax
cleaned_text = re.sub(r'(\*\*|##|#|_|[*])', '', text_with_new_lines)

print(cleaned_text)

 New Employee Questionnaire

Welcome aboard! We're thrilled to have you join our team. This questionnaire is designed to help us get to know you better and ensure a smooth onboarding experience. Please answer the following questions to the best of your ability.

Personal Information:

1. Full Name:
2. Date of Birth:
3. Contact Information:
     Phone Number:
     Email Address:
     Personal Address:
4. Emergency Contact Information:
     Name:
     Relationship:
     Phone Number:
5. Are you authorized to work in [Country/Region]? (Yes/No)
6. Do you have any disabilities that we should be aware of? (Yes/No)
     If yes, please provide details and any reasonable accommodations you require:

Employment History:

7. Previous Employer:
8. Job Title:
9. Dates of Employment:
10. Reason for Leaving:
11. Relevant Skills & Experience:

Position Specific:

12. What are your expectations for this role?
13. What are your strengths and weaknesses related to this position?
14. What are your goals for the first 30/60/90 days in this role?
15. Are there any specific areas of the job you are particularly interested in or excited about?
16. Do you have any prior experience with our company's products/services? (Yes/No)
     If yes, please elaborate:

Company Culture & Team:

17. What are some of your preferred ways to work in a team setting?
18. How do you typically approach new challenges or projects?
19. What are your preferred methods of communication? (Email, phone, in-person, etc.)
20. What is your preferred learning style?

Availability & Schedule:

21. What is your preferred work schedule? (Full-time, part-time, flexible, etc.)
22. Are you available for overtime or weekend work? (Yes/No)

Miscellaneous:

23. Do you have any questions for us?
24. Is there anything else we should know about you that may be relevant to your role?

Thank you for completing this questionnaire. We look forward to having you on board!

Note: This questionnaire is a template and can be customized to fit your specific needs and the requirements of the new position. You can add or remove questions based on your company's culture, industry, and the specific role being filled.

In [2]:
import pandas as pd

In [52]:
df = pd.read_csv('extracted_data.csv',encoding='latin1')

In [53]:
df.sample(5)

,URL,Etiology,Symptoms
7,https://www.orthobullets.com/trauma/322053/ger...,Pathophysiology\nmusculoskeletal related condi...,NaN
119,https://www.orthobullets.com/shoulder-and-elbo...,Pathophysiology\nmechanisms\nunderlying mechan...,pain\ninstability\nweakness\nparesthesias\ncre...
35,https://www.orthobullets.com/basic-science/903...,Pathophysiology\nhypocalcemia\ndue to the inab...,NaN
2,https://www.orthobullets.com/recon/12124/tha-t...,NaN,NaN
236,https://www.orthobullets.com?contentType=1&pp=...,NaN,NaN

In [54]:
df = df.dropna()

In [55]:
df.iloc[0]

URL         https://www.orthobullets.com/spine/2046/ossifi...
Etiology    Pathophysiology\ncause is unclear but likely m...
Symptoms    often asymptomatic\nsymptoms and exam findings...
Name: 0, dtype: object

In [56]:
text = df.iloc[0]['URL']

In [57]:
' '.join(text.split('/')[-1].split('-'))

'ossification posterior longitudinal ligament'

In [58]:
df['Name'] = df['URL'].apply(lambda x: ' '.join(x.split('/')[-1].split('-')))

In [59]:
df

,URL,Etiology,Symptoms,Name
0,https://www.orthobullets.com/spine/2046/ossifi...,Pathophysiology\ncause is unclear but likely m...,often asymptomatic\nsymptoms and exam findings...,ossification posterior longitudinal ligament
1,https://www.orthobullets.com/trauma/1018/elbow...,Pathophysiology\nmechanism for posterolateral ...,pain and swelling,elbow dislocation
8,https://www.orthobullets.com/hand/6036/base-of...,Pathophysiology\nmechanism of injury\nmost Ben...,acute pain at the base of thumb with,base of thumb fractures
9,https://www.orthobullets.com/spine/2016/odonto...,Pathophysiology\nmechanism\ndisplacement may b...,"neck pain\nworse with motion, especially rotat...",odontoid fracture
11,https://www.orthobullets.com/basic-science/410...,Genetics\nHLA markers\nDR4 associated with pol...,morning stiffness and joint pain\nvisual chang...,juvenile idiopathic arthritis
...,...,...,...,...
492,https://www.orthobullets.com/trauma/1059/gun-s...,Pathoanatomy\nwounding capability of a bullet ...,"pain, deformity",gun shot wounds
493,https://www.orthobullets.com/knee-and-sports/3...,Mechanisms\nblow to anteromedial knee\nvarus b...,often have instability symptoms when knee is i...,posterolateral corner injury
494,https://www.orthobullets.com/foot-and-ankle/70...,Pathophysiology\nMTP hyperextension is the pri...,pain at the level of the unstable MTP joint\nm...,claw toe
495,https://www.orthobullets.com/shoulder-and-elbo...,Pathophysiology\nrepetitive stress of pitching...,pain in posteromedial elbow with full extensio...,valgus extension overload pitchers elbow
496,https://www.orthobullets.com/foot-and-ankle/70...,Pathophysiology\nmechanism of injury\nankle in...,pain centered over ankle joint line\njoint eff...,osteochondral lesions of the talus

In [60]:
condition_name = df.iloc[0]['Name']
symptoms = df.iloc[0]['Symptoms']
etiology = df.iloc[0]['Etiology']

prompt = f"""
Create a detailed questionnaire for diagnosing {condition_name}. The questionnaire should be in a multiple-choice format and cover the following aspects:

1. **Symptoms**: Based on the symptoms provided, create questions that help identify the presence and severity of each symptom.
   - Symptoms: {symptoms}

2. **Etiology**: Include questions that explore the possible causes and risk factors associated with the condition.
   - Etiology: {etiology}

Each question should have multiple-choice answers with options.

Ensure the questions are clear, concise, and cover all relevant aspects to accurately diagnose {condition_name}.
"""


data = {
    "contents": [
        {
            "parts": [
                {
                    "text": prompt
                }
            ]
        }
    ]
}

# Make the POST request
response = requests.post(url, headers=headers, json=data)

# Print the response
print(response.json())

{'candidates': [{'content': {'parts': [{'text': '## Ossification of Posterior Longitudinal Ligament (OPLL) Questionnaire\n\n**Please answer the following questions to the best of your ability.  Choose the option that most closely reflects your experience.**\n\n**1. Symptoms:**\n\n**a.  Neck pain:**\n    -  None\n    -  Mild, occasional discomfort\n    -  Moderate, frequent pain\n    -  Severe, constant pain\n\n**b.  Numbness or tingling:**\n    -  None\n    -  Occasional, in hands or fingers\n    -  Frequent, in hands, fingers, or arms\n    -  Constant, in hands, fingers, or arms\n\n**c.  Weakness:**\n    -  None\n    -  Occasional, in hands or fingers\n    -  Frequent, in hands, fingers, or arms\n    -  Constant, in hands, fingers, or arms\n\n**d.  Difficulty with fine motor skills:**\n    -  None\n    -  Occasional, such as buttoning clothes\n    -  Frequent, such as writing or using utensils\n    -  Constant, unable to perform fine motor tasks\n\n**e.  Bowel or bladder control problems:**\n    -  None\n    -  Occasional, such as urinary urgency or incontinence\n    -  Frequent, difficulty controlling bowel movements or urination\n    -  Constant, complete loss of bowel or bladder control\n\n**f.  Gait disturbances:**\n    -  None\n    -  Occasional, feeling unsteady or clumsy\n    -  Frequent, difficulty walking or maintaining balance\n    -  Constant, unable to walk independently\n\n**g.  Have you experienced any other symptoms that you believe may be related to your neck or spine?**\n    -  Yes, please specify: ____________________________________\n    -  No\n\n**2.  Etiology:**\n\n**a.  Do you have a history of diabetes?**\n    -  Yes\n    -  No\n\n**b.  Are you currently obese or have you been obese in the past?**\n    -  Yes\n    -  No\n\n**c.  Do you follow a diet that is high in salt and low in meat?**\n    -  Yes\n    -  No\n\n**d.  Do you have any known conditions that affect calcium absorption?**\n    -  Yes, please specify: ____________________________________\n    -  No\n\n**e.  Have you experienced any significant trauma or repetitive strain to your neck or spine?**\n    -  Yes, please describe: ____________________________________\n    -  No\n\n**f.  Do you engage in any activities that put significant mechanical stress on your neck?**\n    -  Yes, please specify: ____________________________________\n    -  No\n\n**Please note:** This questionnaire is intended as a preliminary screening tool and is not a substitute for professional medical diagnosis. If you are experiencing any of the symptoms described above, please consult with a qualified healthcare professional for further evaluation. \n'}], 'role': 'model'}, 'finishReason': 'STOP', 'index': 0, 'safetyRatings': [{'category': 'HARM_CATEGORY_SEXUALLY_EXPLICIT', 'probability': 'NEGLIGIBLE'}, {'category': 'HARM_CATEGORY_HATE_SPEECH', 'probability': 'NEGLIGIBLE'}, {'category': 'HARM_CATEGORY_HARASSMENT', 'probability': 'NEGLIGIBLE'}, {'category': 'HARM_CATEGORY_DANGEROUS_CONTENT', 'probability': 'NEGLIGIBLE'}]}], 'usageMetadata': {'promptTokenCount': 172, 'candidatesTokenCount': 628, 'totalTokenCount': 800}}

In [61]:
text = response.json()['candidates'][0]['content']['parts'][0]['text']
# Assuming 'text' is a string variable containing the text with Markdown syntax
text_with_new_lines = text.replace('\\n', '\n')

# Remove common Markdown syntax
cleaned_text = re.sub(r'(\*\*|##|#|_|[*])', '', text_with_new_lines)

print(cleaned_text)

 Ossification of Posterior Longitudinal Ligament (OPLL) Questionnaire

Please answer the following questions to the best of your ability.  Choose the option that most closely reflects your experience.

1. Symptoms:

a.  Neck pain:
    -  None
    -  Mild, occasional discomfort
    -  Moderate, frequent pain
    -  Severe, constant pain

b.  Numbness or tingling:
    -  None
    -  Occasional, in hands or fingers
    -  Frequent, in hands, fingers, or arms
    -  Constant, in hands, fingers, or arms

c.  Weakness:
    -  None
    -  Occasional, in hands or fingers
    -  Frequent, in hands, fingers, or arms
    -  Constant, in hands, fingers, or arms

d.  Difficulty with fine motor skills:
    -  None
    -  Occasional, such as buttoning clothes
    -  Frequent, such as writing or using utensils
    -  Constant, unable to perform fine motor tasks

e.  Bowel or bladder control problems:
    -  None
    -  Occasional, such as urinary urgency or incontinence
    -  Frequent, difficulty controlling bowel movements or urination
    -  Constant, complete loss of bowel or bladder control

f.  Gait disturbances:
    -  None
    -  Occasional, feeling unsteady or clumsy
    -  Frequent, difficulty walking or maintaining balance
    -  Constant, unable to walk independently

g.  Have you experienced any other symptoms that you believe may be related to your neck or spine?
    -  Yes, please specify:
    -  No

2.  Etiology:

a.  Do you have a history of diabetes?
    -  Yes
    -  No

b.  Are you currently obese or have you been obese in the past?
    -  Yes
    -  No

c.  Do you follow a diet that is high in salt and low in meat?
    -  Yes
    -  No

d.  Do you have any known conditions that affect calcium absorption?
    -  Yes, please specify:
    -  No

e.  Have you experienced any significant trauma or repetitive strain to your neck or spine?
    -  Yes, please describe:
    -  No

f.  Do you engage in any activities that put significant mechanical stress on your neck?
    -  Yes, please specify:
    -  No

Please note: This questionnaire is intended as a preliminary screening tool and is not a substitute for professional medical diagnosis. If you are experiencing any of the symptoms described above, please consult with a qualified healthcare professional for further evaluation.

In [62]:
def generate_questionnaire(row):
    condition_name = row['Name']
    symptoms = row['Symptoms']
    etiology = row['Etiology']

    prompt = f"""
    Create a detailed questionnaire for diagnosing {condition_name}. The questionnaire should be in a multiple-choice format and cover the following aspects:

    1. **Symptoms**: Based on the symptoms provided, create questions that help identify the presence and severity of each symptom.
       - Symptoms: {symptoms}

    2. **Etiology**: Include questions that explore the possible causes and risk factors associated with the condition.
       - Etiology: {etiology}

    Each question should have multiple-choice answers with options.

    Ensure the questions are clear, concise, and cover all relevant aspects to accurately diagnose {condition_name}.
    """

    data = {
        "contents": [
            {
                "parts": [
                    {
                        "text": prompt
                    }
                ]
            }
        ]
    }

    # Make the POST request
    response = requests.post(url, headers=headers, json=data)
    # print(response.json())
    try:
        text = response.json()['candidates'][0]['content']['parts'][0]['text']
    except KeyError:
        text = "Error: Missing expected keys in the response."
    # text = response.json()['candidates'][0]['content']['parts'][0]['text']
    # Assuming 'text' is a string variable containing the text with Markdown syntax
    text_with_new_lines = text.replace('\\n', '\n')

    # Remove common Markdown syntax
    cleaned_text = re.sub(r'(\*\*|##|#|_|[*])', '', text_with_new_lines)

    return cleaned_text
    # return response.json()

In [63]:

df['Questionnaire'] = None

for index, row in df.iterrows():
    if index % 10 == 0:
        print(f"Processing row {index}...")
    if df['Questionnaire'][index] is not None:
        continue
    questionnaire = generate_questionnaire(row)
    df['Questionnaire'][index] = questionnaire
    
df.to_csv('questionnaires.csv', index=False)

Processing row 0...
Processing row 30...
Processing row 40...
Processing row 60...
Processing row 80...
Processing row 100...
Processing row 110...
Processing row 120...
Processing row 130...
Processing row 140...
Processing row 150...
Processing row 180...
Processing row 200...
Processing row 230...
Processing row 240...
Processing row 250...
Processing row 260...
Processing row 270...
Processing row 290...
Processing row 300...
Processing row 350...
Processing row 360...
Processing row 380...
Processing row 400...
Processing row 410...
Processing row 420...
Processing row 430...
Processing row 440...
Processing row 470...

In [3]:
import warnings
warnings.filterwarnings("ignore")

In [66]:
df['Questionnaire'][0]

" Ossification Posterior Longitudinal Ligament (OPLL) Questionnaire\n\nThis questionnaire is intended for informational purposes only and does not constitute medical advice. Please consult with a qualified healthcare professional for diagnosis and treatment.\n\n1. Symptoms:\n\n1.1 Do you experience any of the following symptoms?\n\n    a) Numbness or tingling in your hands or feet\n    b) Weakness in your arms or legs\n    c) Difficulty walking or balance issues\n    d) Pain in your neck or back\n    e) Bowel or bladder dysfunction\n    f) Difficulty with fine motor skills\n    g) None of the above\n\n1.2 If you experience any of the symptoms above, how often do you experience them?\n\n    a) Occasionally\n    b) Frequently\n    c) Constantly\n\n1.3 How would you rate the severity of your symptoms?\n\n    a) Mild\n    b) Moderate\n    c) Severe\n\n2. Etiology:\n\n2.1 Do you have a history of any of the following conditions?\n\n    a) Diabetes\n    b) Obesity\n    c) High blood pressure\n    d) High cholesterol\n    e) Thyroid disorders\n    f) None of the above\n\n2.2 Do you follow a specific diet?\n\n    a) High salt, low meat diet\n    b) Low salt, high meat diet\n    c) Vegetarian diet\n    d) Other (please specify)\n    e) No specific diet\n\n2.3 Do you have any factors that may contribute to poor calcium absorption?\n\n    a) Vitamin D deficiency\n    b) Celiac disease\n    c) Crohn's disease\n    d) Other (please specify)\n    e) None of the above\n\n2.4 Do you engage in activities that put significant mechanical stress on your spine?\n\n    a) Heavy lifting\n    b) Repetitive motions\n    c) Contact sports\n    d) Other (please specify)\n    e) None of the above\n\n3. Additional Information:\n\n3.1 Have you ever had any spinal surgeries?\n\n    a) Yes\n    b) No\n\n3.2 Have you had any previous imaging studies of your spine (e.g., X-ray, MRI)?\n\n    a) Yes\n    b) No\n\n3.3 Please provide any relevant information about your family history of spinal conditions.\n\nPlease note: This questionnaire is not a substitute for a medical evaluation. It is important to consult with a qualified healthcare professional for a proper diagnosis and treatment plan.  \n"

In [67]:
text = df['Questionnaire'][0]

In [69]:
text

" Ossification Posterior Longitudinal Ligament (OPLL) Questionnaire\n\nThis questionnaire is intended for informational purposes only and does not constitute medical advice. Please consult with a qualified healthcare professional for diagnosis and treatment.\n\n1. Symptoms:\n\n1.1 Do you experience any of the following symptoms?\n\n    a) Numbness or tingling in your hands or feet\n    b) Weakness in your arms or legs\n    c) Difficulty walking or balance issues\n    d) Pain in your neck or back\n    e) Bowel or bladder dysfunction\n    f) Difficulty with fine motor skills\n    g) None of the above\n\n1.2 If you experience any of the symptoms above, how often do you experience them?\n\n    a) Occasionally\n    b) Frequently\n    c) Constantly\n\n1.3 How would you rate the severity of your symptoms?\n\n    a) Mild\n    b) Moderate\n    c) Severe\n\n2. Etiology:\n\n2.1 Do you have a history of any of the following conditions?\n\n    a) Diabetes\n    b) Obesity\n    c) High blood pressure\n    d) High cholesterol\n    e) Thyroid disorders\n    f) None of the above\n\n2.2 Do you follow a specific diet?\n\n    a) High salt, low meat diet\n    b) Low salt, high meat diet\n    c) Vegetarian diet\n    d) Other (please specify)\n    e) No specific diet\n\n2.3 Do you have any factors that may contribute to poor calcium absorption?\n\n    a) Vitamin D deficiency\n    b) Celiac disease\n    c) Crohn's disease\n    d) Other (please specify)\n    e) None of the above\n\n2.4 Do you engage in activities that put significant mechanical stress on your spine?\n\n    a) Heavy lifting\n    b) Repetitive motions\n    c) Contact sports\n    d) Other (please specify)\n    e) None of the above\n\n3. Additional Information:\n\n3.1 Have you ever had any spinal surgeries?\n\n    a) Yes\n    b) No\n\n3.2 Have you had any previous imaging studies of your spine (e.g., X-ray, MRI)?\n\n    a) Yes\n    b) No\n\n3.3 Please provide any relevant information about your family history of spinal conditions.\n\nPlease note: This questionnaire is not a substitute for a medical evaluation. It is important to consult with a qualified healthcare professional for a proper diagnosis and treatment plan.  \n"

In [7]:
df = pd.read_excel('questionnaires Spine.xlsx')
df

,URL,Etiology,Symptoms,Name,Questionnaire
0,https://www.orthobullets.com/spine/2046/ossifi...,Pathophysiology\ncause is unclear but likely m...,often asymptomatic\nsymptoms and exam findings...,ossification posterior longitudinal ligament,Ossification Posterior Longitudinal Ligament ...
1,https://www.orthobullets.com/spine/2016/odonto...,Pathophysiology\nmechanism\ndisplacement may b...,"neck pain\nworse with motion, especially rotat...",odontoid fracture,Odontoid Fracture Questionnaire\n\nPlease ans...
2,https://www.orthobullets.com/spine/2066/synovi...,Pathophysiology\npossible etiologies\ntrauma (...,mechanical back pain\nradicular symptoms\n(leg...,synovial facet cyst,Synovial Facet Cyst Questionnaire\n\nPlease a...
3,https://www.orthobullets.com/spine/2030/cervic...,Pathophysiology\ncauses\ndegenerative cervical...,occipital headache (\ncommon)\ntrapezial or in...,cervical radiculopathy,Cervical Radiculopathy Questionnaire\n\nPleas...
4,https://www.orthobullets.com/spine/2037/lumbar...,Mechanism\nNarrowing of the lumbar spinal cana...,back pain\nreferred buttock pain\nleg pain\nof...,lumbar spinal stenosis,Lumbar Spinal Stenosis Questionnaire\n\nThis ...
5,https://www.orthobullets.com/spine/422812/sacr...,Pathophysiology\nidiopathic mechanism is the m...,pain patterns\npain usually present\njust infe...,sacroiliac joint dysfunction,Sacroiliac Joint Dysfunction Questionnaire\n\...
6,https://www.orthobullets.com/spine/2031/cervic...,Pathophysiology\netiology\ndegenerative cervic...,neck pain and stiffness\naxial neck pain (ofte...,cervical myelopathy,Cervical Myelopathy Questionnaire\n\nThis que...
7,https://www.orthobullets.com/spine/2041/adult-...,Types\ncoronal plane imbalance\ndefined as lat...,low back pain (40-90%)\ncommonest symptom is l...,adult spinal deformity,Adult Spinal Deformity Questionnaire\n\nPleas...
8,https://www.orthobullets.com/spine/2044/ankylo...,"Pathoanatomy\nexact mechanism is unknown, but ...",lumbosacral pain and stiffness\npresent in mos...,ankylosing spondylitis,Ankylosing Spondylitis Questionnaire\n\nThis ...
9,https://www.orthobullets.com/spine/2059/pathol...,Causes\nosteoid osteomas\noccur in the apex of...,back pain\nmost commonly at night\npain reliev...,pathologic scoliosis,Pathologic Scoliosis Questionnaire\n\nThis qu...
10,https://www.orthobullets.com/spine/2021/osteop...,Pathoanatomy\nosteoporosis\ncharacteristics\nb...,pain\n25% of VCF are painful enough that patie...,osteoporotic vertebral compression fracture,Osteoporotic Vertebral Compression Fracture Q...
11,https://www.orthobullets.com/spine/2058/pediat...,Pathophysiology\nconditions represent a contin...,asymptomatic\nmany cases of spondylolysis are ...,pediatric spondylolysis and spondylolisthesis,Pediatric Spondylolysis and Spondylolisthesis...
12,https://www.orthobullets.com/spine/2064/cervic...,Pathoanatomy\nrepresent spectrum of osteoligam...,pain\nneck pain in setting of flexion-distract...,cervical facet dislocations and fractures,Cervical Facet Dislocations and Fractures Que...
13,https://www.orthobullets.com/spine/2026/spinal...,Pathophysiology\norigin\nhematogenous spread ~...,systemic illness more profound than patients w...,spinal epidural abscess,Spinal Epidural Abscess Questionnaire\n\nThis...
14,https://www.orthobullets.com/spine/2025/adult-...,Pathophysiology\npathogens\nbacterial\nstaph a...,fever is only present in 1/3\nof patients\npai...,adult pyogenic vertebral osteomyelitis,Questionnaire for Diagnosing Adult Pyogenic V...
15,https://www.orthobullets.com/spine/2050/atlant...,Mechanism\nspectrum of disease that ranges fro...,tilted head\nneck pain\nheadache,atlantoaxial rotatory displacement aard,Atlantoaxial Rotatory Displacement (AARD) Que...
16,https://www.orthobullets.com/spine/2038/adult-...,Pathophysiology\nforaminal stenosis\nadult ist...,axial back pain\nmost common presentation\npai...,adult isthmic spondylolisthesis,Adult Isthmic Spondylolisthesis Questionnaire...
17,https://www.orthobullets.com/spine/2036/discog...,Mechanism\ndisc characteristics modified by bo...,axial low back pain without radicular symptoms...,discogenic back pain,Discogenic Back Pain Questionnaire\n\nPlease ...
18,https://www.orthobullets.com/foot-and-ankle/70...,Mechanism and pathophysiology\ntheories\nneuro...,"swollen foot and ankle\npain in 50%, painless ...",diabetic charcot neuropathy,Diabetic Charcot Neuropathy Questionnaire\n\n...
19,https://www.orthobullets.com/spine/2039/degene...,Pathoanatomy\nforward subluxation (intersegmen...,mechanical/ back pain\nmost common presenting ...,degenerative spondylolisthesis,Degenerative Spondylolisthesis Questionnaire\...
20,https://www.orthobullets.com/spine/2034/low-ba...,Mechanism\nmuscle strain\nmost common cause of...,axial pain\nmusculogenic\nmost common cause of...,low back pain introduction,Low Back Pain Assessment Questionnaire: Intro...
21,https://www.orthobullets.com/spine/2061/scheue...,Pathoanatomy\nexact pathophysiology is unknown...,may complain of thoracic or lumbar pain\ncosme...,scheuermanns kyphosis,Scheuermann's Kyphosis Questionnaire\n\nThis ...
22,https://www.orthobullets.com/pathology/2009/me...,Pathophysiology\nmechanism of bone destruction...,History\nunexplained rest pain or mechanical b...,metastatic disease of spine,Questionnaire for Diagnosing Metastatic Disea...
23,https://www.orthobullets.com/knee-and-sports/3...,Mechanism\naxial load (compression) with flexi...,neck pain\nneurological symptoms such as numbn...,neck injuries in athletes,Neck Injury Questionnaire for Athletes\n\nPle...
24,https://www.orthobullets.com/spine/2052/congen...,Pathophysiology\ncontracture of the sternoclei...,head tilt and rotation\npainless passive motion,congenital muscular torticollis,Congenital Muscular Torticollis Questionnaire...
25,https://www.orthobullets.com/spine/2035/lumbar...,Pathoanatomy\nrecurrent torsional strain leads...,can present with symptoms of\naxial back pain\...,lumbar disc herniation,Lumbar Disc Herniation Questionnaire\n\nPleas...

In [10]:
import re
combined_prompt = """
Create a combined diagnostic questionnaire in a multiple-choice format that can differentiate between multiple medical conditions. The following conditions and their associated symptoms and etiologies should be included:

"""

# Adding each condition and its details to the prompt
for index, row in df.iterrows():
    condition_name = row['Name']
    symptoms = row['Symptoms']
    etiology = row['Etiology']

    prompt = f"""
    Condition: {condition_name}
    Symptoms: {symptoms}
    Etiology: {etiology}
    """
    combined_prompt += prompt + "\n"

combined_prompt += """
Instructions for the questionnaire:
- For **each question**, ensure it can help in identifying one or more of the above conditions.
- The questionnaire should ask about **symptoms**, **possible causes**, and **risk factors** common across the conditions.
- Each question should be in multiple-choice format and designed in such a way that it can help distinguish between these conditions based on the selected answers.
- Ensure that each question addresses the presence, frequency, severity, or nature of symptoms and possible causes in a way that would help in differentiating the conditions.
- Provide clear and concise multiple-choice options for each question.

The goal of the questionnaire is to accurately identify which of these conditions a person might be suffering from based on their responses.
also, give the possible combinations of answers which can lead to a particular diagnosis.
"""

# Define the request data
data = {
    "contents": [
        {
            "parts": [
                {
                    "text": combined_prompt
                }
            ]
        }
    ]
}

# Make the POST request
response = requests.post(url, headers=headers, json=data)
# print(response.json())
try:
     text = response.json()['candidates'][0]['content']['parts'][0]['text']
except KeyError:
     text = "Error: Missing expected keys in the response."
# text = response.json()['candidates'][0]['content']['parts'][0]['text']
# Assuming 'text' is a string variable containing the text with Markdown syntax
text_with_new_lines = text.replace('\\n', '\n')

# Remove common Markdown syntax
cleaned_text = re.sub(r'(\*\*|##|#|_|[*])', '', text_with_new_lines)

print(cleaned_text)

 Combined Diagnostic Questionnaire for Spine Conditions:

Instructions: Please answer each question honestly and to the best of your ability. Choose the most appropriate response from the provided options.

1. What is your primary symptom?

a) Neck pain
b) Back pain
c) Buttock pain
d) Leg pain
e) Neck stiffness
f) Headache

2.  When is your pain worse?

a) In the morning
b) After activity
c) When standing for prolonged periods
d) When sitting for prolonged periods
e) When walking
f) When bending forward
g) When extending your back
h) At night
i) With neck movement

3. Where is your pain located?

a) Upper back
b) Lower back
c) Neck
d) Buttocks
e) Legs (specify location: unilateral or bilateral, which leg(s))
f)  Occipital region

4. Do you experience any of the following neurological symptoms?

a) Numbness or tingling in your arms or legs
b) Weakness in your arms or legs
c) Difficulty with hand dexterity (dropping objects, difficulty manipulating fine objects)
d) Difficulty with grip strength
e) Difficulty with overhead activities
f) Gait instability
g) Bowel or bladder dysfunction
h) Difficulty with horizontal gaze

5.  Do you experience any of the following systemic symptoms?

a) Fever
b) Weight loss
c) Fatigue
d) Malaise
e) Shortness of breath

6.  Do you have a history of any of the following?

a) Trauma (e.g., car accident, fall, sports injury)
b) Surgery to the spine
c) Prior infection
d) Cancer
e) Diabetes
f) Rheumatoid arthritis
g)  Osteoporosis

7.  Do you have any of the following risk factors?

a) Obesity
b) Smoking
c)  High salt-low meat diet
d) Poor calcium absorption
e)  Prolonged sitting
f)  Repetitive heavy lifting

8.  Is your pain relieved by any of the following?

a) Rest
b) Sitting
c) Leaning forward
d) Tight fitting belt
e)  Anti-inflammatory medications

Possible Diagnosis Combinations:

Cervical Radiculopathy:  1a, 1e, 4a, 4b, 4d, 4e, 6a, 8a

Cervical Myelopathy:  1a, 1e, 4c, 4f, 4g, 8a

Ossification of the Posterior Longitudinal Ligament (OPLL): 1a, 1e, 4c, 4f, 4g, 6g

Odontoid Fracture: 1a, 1i, 2i, 6a

Cervical Facet Dislocations and Fractures: 1a, 1i, 4a, 4b, 6a

Adult Spinal Deformity:  1b, 1c, 1d, 2c, 2g, 4a, 4b, 6a, 6g, 8a, 8b

Ankylosing Spondylitis: 1a, 1b, 1e, 2a, 4h, 5e, 6f

Pathologic Scoliosis: 1b, 2h, 6d, 8e

Osteoporotic Vertebral Compression Fracture: 1b, 2h, 6g, 8a, 8e

Pediatric Spondylolysis and Spondylolisthesis:  1b, 2b, 2g, 4a, 4b, 4f, 4g

Lumbar Spinal Stenosis:  1b, 1c, 1d, 2c, 2e, 2g, 4a, 4b, 4f, 4g, 6g, 8a, 8b, 8c

Sacroiliac Joint Dysfunction: 1b, 1c, 1d, 2b, 2g, 8d

Spinal Epidural Abscess: 1b, 2h, 4a, 4b, 5a, 6c

Adult Pyogenic Vertebral Osteomyelitis: 1b, 2h, 4a, 4b, 5a, 6c

Atlantoaxial Rotatory Displacement (AARD): 1a, 1i, 6f, 6c

Adult Isthmic Spondylolisthesis: 1b, 2b, 2g, 4a, 4b, 8a

Discogenic Back Pain: 1b, 2f, 8a

Diabetic Charcot Neuropathy: 1b, 1c, 1d, 2b, 4a, 5b, 6e

Degenerative Spondylolisthesis: 1b, 1c, 1d, 2c, 2g, 4a, 4b, 4f, 4g, 8a, 8b

Low Back Pain: 1b, 2b, 2f, 2g, 4a, 4b, 4f, 4g, 6a, 6b, 6d, 6e, 6g, 8a, 8b

Scheuermanns Kyphosis: 1b, 2a, 4a, 4b, 6a, 6b, 6g

Metastatic Disease of Spine: 1b, 2h, 4a, 4b, 5a, 5b, 5c, 5d, 6d

Neck Injuries in Athletes: 1a, 1i, 4a, 4b, 6a, 6b

Congenital Muscular Torticollis: 1a, 1e, 6a, 6b

Lumbar Disc Herniation: 1b, 1c, 1d, 2d, 2f, 4a, 4b, 4f, 4g, 6g, 8a

Please note: This questionnaire is for educational purposes only and is not a substitute for professional medical advice. If you are experiencing any of these symptoms, it is crucial to consult with a healthcare professional for an accurate diagnosis and appropriate treatment plan.